notes/models.py
from notes import db 
from flask_login import UserMixin
from sqlalchemy.sql import func


class Note(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    data = db.Column(db.String(10000))
    date = db.Column(db.DateTime(timezone=True), default=func.now())
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

    def __repr__(self):
        return f"Note('{self.data}', '{self.date}')"


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(150), nullable = False, unique=True)
    password = db.Column(db.String(150), nullable = False)
    username = db.Column(db.String(150), nullable = False)
    notes = db.relationship('Note')

    def __repr__(self):
        return f"User('{self.email}', '{self.username}')"

notes/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
import os 
    
db = SQLAlchemy()

def retrieve_secrets(project_id, secret_ids):
    """
    Retrieve multiple secrets from the Secret Manager and return them as a dictionary.
    project_id: The ID of the GCP project where the secrets are stored.
    secret_ids: A list of secret IDs to retrieve.
    """
    from google.cloud import secretmanager
    client = secretmanager.SecretManagerServiceClient()
    secrets = {}
    for secret_id in secret_ids:
        name = f"projects/{project_id}/secrets/{secret_id}/versions/latest"
        try:
            response = client.access_secret_version(request={"name": name})
            payload = response.payload.data.decode("UTF-8")
            secrets[secret_id] = payload
        except Exception as e:
            print(f'Error occured while accessing secret {secret_id} : {e}')
    return secrets


def create_app():

     app = Flask(__name__)

     project_id = 'huddle-project-flask'
     secret_ids = ['SECRET_KEY','SQLALCHEMY_DATABASE_URI']
     secrets = retrieve_secrets(project_id, secret_ids)
     connection_name = os.environ.get("CONNECTION_NAME")

     app.config['SECRET_KEY'] = os.environ.get('SECRET_KEY')
     
     if os.environ.get('TESTING'):
          app.config['SQLALCHEMY_DATABASE_URI'] = os.environ.get('SQLALCHEMY_DATABASE_TEST_URI')
          app.config['SECRET_KEY'] = os.environ.get('SECRET_KEY')
     else:
          app.config['SQLALCHEMY_DATABASE_URI']= secrets["SQLALCHEMY_DATABASE_URI"]
          app.config['SECRET_KEY'] = secrets["SECRET_KEY"]

     db.init_app(app)

     from notes.views import views
     from notes.auth import auth

     app.register_blueprint(views, url_prefix='/')
     app.register_blueprint(auth, url_prefix='/')

     from notes.models import User, Note

     with app.app_context():
          db.create_all()
     
     login_manager = LoginManager()
     login_manager.login_view = 'auth.login'
     login_manager.init_app(app)

     @login_manager.user_loader
     def load_user(id):
          # by default it will look at the primary key
          return User.query.get(int(id))

     return app

notes/auth.py
from flask import Blueprint,render_template, request, flash, redirect,url_for
from notes.models import User
from werkzeug.security import generate_password_hash, check_password_hash
from notes import db
from flask_login import login_user, login_required, logout_user, current_user


auth = Blueprint('auth',__name__)

@auth.route('/login', methods=['GET','POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        user = User.query.filter_by(email=email).first()

        if user:
            if check_password_hash(user.password, password):
                flash('Logged in Succcessfully!',category='success')
                login_user(user, remember=True)
                return redirect(url_for('views.home'))
            else:
                flash('Incorrect password, try again', category='error')
        else:
            flash('Email does not exist',category='error')


    return render_template("login.html", user=current_user)

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

@auth.route('/sign-up', methods=['GET','POST'])
def sign_up():
    if request.method == 'POST':
        email = request.form.get('email')
        username = request.form.get('username')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')
        
        user = User.query.filter_by(email=email).first()

        if user:
            flash('User Already Exist',category='error')
        elif len(email) < 5:
            flash('Email must be greater than 4 characters.', category='error')
        elif len(username) < 5:
            flash('Username must be greater than 4 characters.', category='error')
        elif password1 != password2:
            flash('Passwords do not match ', category='error')
        elif len(password1) < 7:
            flash('Password must be greater than 6 characters.', category='error')
        else:
            new_user = User(email=email, username=username, password=generate_password_hash(password1, method='sha256'))
            flash('Account has been successfully created', category='success')
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user)
            return redirect(url_for('views.home'))
  
    return render_template("signup.html", user=current_user)

notes/views.py
from flask import Blueprint, render_template, request, flash, redirect, url_for, session, abort
from flask_login import login_required, current_user
from notes.models import Note
from notes import db
from pytz import timezone
from datetime import datetime

views = Blueprint('views',__name__)


@views.route('/', methods = ["GET","POST"])
@login_required
def home ():
    if request.method == "POST":
        note = request.form.get("note")
        if len(note) < 4:
            flash("The note must be longer than 3 characters",category="error")
        else:
            madrid_timezone = timezone('Europe/Madrid')
            madrid_time = datetime.now(madrid_timezone)
            new_note = Note(data=note, user_id = current_user.id,date=madrid_time)
            db.session.add(new_note)
            db.session.commit()

    return render_template("home.html", user= current_user)

@views.route("/delete/<int:note_id>", methods=["GET","POST"])
@login_required
def delete_post(note_id):
    note = Note.query.get(note_id)
    if note:
        if note.user_id == current_user.id:
            db.session.delete(note)
            db.session.commit()
            flash('Your post has been successfully deleted','success')
    return redirect(url_for('views.home'))

@views.route("/update/<int:note_id>", methods=["POST"])
@login_required
def get_note(note_id):
   session['note_id'] = note_id 
   note = Note.query.get(note_id)
   return render_template("edit.html", user=current_user, note=note)
    
@views.route("/update", methods=["POST","GET"])
@login_required
def update_note():
   note_id = session.get('note_id')
   note = Note.query.get(note_id)
   if request.method == 'POST' :
    if note.user_id == current_user.id:
        update_note = request.form.get('note')
        note.data = update_note
        madrid_timezone = timezone('Europe/Madrid')
        madrid_time = datetime.now(madrid_timezone)
        note.date = madrid_time
        db.session.commit()
        return redirect(url_for('views.home'))
    else:
        abort(403)
   else:
    return render_template ("home.html", user=current_user)
    
    
    
    
    

notes/templates/edit.html
{% extends "layout.html" %}
{% block title %}Update Note{% endblock %}
{% block content%}
<div class="container" >
    <h1>Notes</h1>
    <form method="POST" action="{{ url_for('views.update_note') }}">
      <div class="form-group">
        <input type="text" class="form-control" id="task-name" name="note" value="{{ note.data }}">
      </div>
      <br />
      <button type="submit" id="save-changes-btn" class="btn btn-primary" style="padding: 5px" >Save Changes</button>

    </form>
{% endblock %}

notes/templates/home.html
{% extends "layout.html" %}
{% block title %}Home{% endblock %}

{% block content%}
<div class="container" >
    <h1>Notes</h1>
    <form method="POST">
      <div class="form-group">
        <input type="text" class="form-control" id="task-name" name="note" placeholder="Enter task name">
      </div>
      <br />
      <button type="submit" class="btn btn-primary" style="padding: 5px" >Add Note</button>
    </form>
<br />
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Note</th>
          <th>Action</th>
          <th>Date </th>
        </tr>
      </thead>
      <tbody>
        {% for note in user.notes %}
        <tr>
          <td>{{ note.data }}</td>
          <td>
            <div class="row">
              <div class="col-3">
                <form method="POST" action="{{ url_for('views.get_note', note_id=note.id) }}">
                  <button class="btn btn-success btn-sm" type="submit">Update</button>
                </form>
              </div>
              <div class="col-3">
                <button type="button" class="btn btn-danger btn-sm" data-bs-toggle="modal" data-bs-target="#deleteModal">
                  Delete
                </button>
              </div>
            </div>
            
                       
            <!-- Modal -->
            <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                    <h1 class="modal-title fs-5" id="deleteModalLabel">Delete Confirmation</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                  </div>
                  <div class="modal-body">
                    Are you sure you want to delete this item?
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary btn-sm" data-bs-dismiss="modal">Close</button>
                    <form method="POST" action="{{ url_for('views.delete_post', note_id=note.id) }}">
                      <button class="btn btn-danger btn-sm" type="submit">Delete</button>
                    </form>
                  </div>
                </div>
              </div>
            </div>
          </td>

          <td>{{ note.date.strftime("%Y-%m-%d %H:%M") }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}

notes/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<link rel="stylesheet" href="/static/styles.css">
  <title>{% block title %}Notes{% endblock %}</title>
</head>
<body>
    
  <nav class="navbar navbar-expand-lg navbar-dark visible ">
        <div class="container-fluid">
          <a class="navbar-brand mr-auto" href="#">NotesLog</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ml-auto">
        {% if user.is_authenticated %}
        <li class="nav-item active">
          <a class="nav-link" href="/">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/logout">Logout</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="/login">Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/sign-up">Sign Up</a>
        </li>
        {% endif %}
      </ul>
    </div>
        </div>
  </nav>

  <!-- Flash code to display a message-->
  {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %} {% for category, message in messages %} {% if category ==
    'error' %}
    <div class="alert alert-danger alter-dismissable fade show" role="alert">
      {{ message }}
    </div>
    {% else %}
    <div class="alert alert-success alter-dismissable fade show" role="alert">
      {{ message }}
    </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %}

  <div class="container" style="padding: 40px;">
    {% block content%}
    {% endblock %}
  </div>
    <!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>
</html>

notes/templates/login.html
{% extends "layout.html" %}
{% block title %}Login{% endblock %}

{% block content%}
<h1 class="display-4 text-center text-sm">Login</h1>
<form method="POST">
    <div class="mb-3">
      <label for="email">Email address</label>
      <input type="email" class="form-control" id="email" name="email" aria-describedby="emailHelp">
      <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
    </div>
    <div class="mb-3">
      <label for="password">Password</label>
      <input type="password" class="form-control" id="password" name="password">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>

{% endblock %}

notes/templates/signup.html
{% extends "layout.html" %}
{% block title %}Sign Up{% endblock %}

{% block content%}
<h1 class="display-4 text-center text-sm">Sign Up</h1>
<form method="POST" action="/sign-up">
    <div class="mb-3">
      <label for="email">Email address</label>
      <input type="email" class="form-control" id="email" name="email" aria-describedby="emailHelp">
      <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
    </div>
    <div class="mb-3">
        <label for="username">Username</label>
        <input  class="form-control" id="username" name="username">
      </div>
    <div class="mb-3">
      <label for="password1">Password</label>
      <input type="password" class="form-control" id="password1" name="password1">
    </div>
    <div class="mb-3">
        <label for="password2">Confirm your password</label>
        <input type="password" class="form-control" id="password2" name="password2">
      </div>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
  
{% endblock %}